### ISSUE TITLE
Gradient image changes every time it's opened from Texture Ramp shading.

### ISSUE THREAD

**Issue by BluWizard10** [Thryrallo/ThryEditor#104] opened 2024-11-01 17:22 UTC
See Video link, courtesy of community member Yoko. https://i.gyazo.com/66f930855ae77120fd1e7fc9f4f443de.mp4

**Comment by Thryrallo** [comment] 2024-11-07 01:25
Yes, this is intended behaviour.
If the input ramp isn't known (the texture in the gradient slot, does not have a serialized gradient in the Thry/gradient file) then the gradient editor try to estimate the gradient from the texture.
The user in this video did not do any edits to the gradient in the editor, so the editor did not save / overwrite his texture when closing the editor. So the preview of the estimate gradient get's discareded and the old texture get's shown.

**Closed by Thryrallo** 2024-11-07 01:25 UTC
Labels: Gradient Editor
